name: SonarCloud Scan

on:
  pull_request:
    branches:
      - '*'

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SonarCloud
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        project-key: WebdriverIO
        organization: vinodkumar0099

    - name: Build and Analyze
      run: |
        # Replace the following command with your build command
        # Example for Maven project:
        mvn clean verify sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

